create or replace database MYDB;
CREATE SCHEMA IF NOT EXISTS MYDB.MYSCHEMA;
USE SCHEMA MYDB.MYSCHEMA;
CREATE OR REPLACE TABLE USER(
ID INTEGER,
NAME VARCHAR(50),
LOCATION VARCHAR(50),
EMAIL VARCHAR(50)
)
CREATE OR REPLACE STORAGE INTEGRATION my_s3_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::158516431615:role/s3-snowflake'
STORAGE_ALLOWED_LOCATIONS = ('s3://s3-snowflake-7/');
DESC INTEGRATION my_s3_integration;
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER='\n'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE my_s3_stage
STORAGE_INTEGRATION = my_s3_integration
URL = 's3://s3-snowflake-7/'
FILE_FORMAT = MY_CSV_FORMAT;

LIST @MY_S3_STAGE

COPY INTO USER FROM @MY_S3_STAGE
FILE_FORMAT = (FORMAT_NAME= MY_CSV_FORMAT);
SELECT * FROM USER;








